CREATE TABLE `betdate_lottery` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `buyid` varchar(45) DEFAULT NULL COMMENT '注單編號',
  `username` varchar(45) DEFAULT NULL COMMENT '會員名稱',
  `CODE` varchar(20) DEFAULT NULL COMMENT '玩法類別',
  `playkey` varchar(20) DEFAULT NULL COMMENT '彩票種類',
  `list_id` varchar(30) DEFAULT NULL COMMENT '玩法代碼',
  `period` varchar(30) DEFAULT NULL COMMENT '期號',
  `number` mediumtext DEFAULT NULL COMMENT '投注號碼',
  `nums` int(11) DEFAULT NULL COMMENT '注數',
  `money` decimal(12,2) DEFAULT NULL COMMENT '下注金額',
  `pri_money` decimal(12,2) DEFAULT NULL COMMENT '中獎金額',
  `z_buy_rate` varchar(60) DEFAULT NULL COMMENT '投注時賠率',
  `pri_number` varchar(300) DEFAULT NULL COMMENT '中獎號碼',
  `modes` varchar(12) DEFAULT NULL COMMENT '下注模式 有角、元、分、厘',
  `z_number` varchar(30) DEFAULT NULL COMMENT '追單單碼(空值為正常單,有值>0為追號單號,追號單號一樣的為同一組單)',
  `STATUS` int(11) DEFAULT NULL COMMENT '訂單狀態(0未派彩 1未中獎 2已中獎 4徹單中 9已撤單49未成立單)',
  `created_at` datetime DEFAULT NULL COMMENT '下注時間',
  `prize_time` datetime DEFAULT NULL COMMENT '派彩時間',
  `prize_date` datetime DEFAULT NULL COMMENT '報表時間(計入那個日期的帳)',
  `handicaps` varchar(1) DEFAULT NULL COMMENT '盤口值(當前下注的是什麼盤口)',
  `currency` varchar(250) NOT NULL COMMENT '幣值',
  `currency_diff` float DEFAULT NULL COMMENT '匯差',
  `buyid_Hash` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IPX_buyid` (`buyid_Hash`)
) ENGINE=InnoDB AUTO_INCREMENT=74009988 DEFAULT CHARSET=utf8