CREATE TABLE `betdata_rich88` (
  `orderid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `record_id_hash` bigint(20) unsigned NOT NULL,
  `record_id` varchar(60) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `game_code` varchar(60) DEFAULT NULL,
  `account` varchar(60) DEFAULT NULL,
  `bet_status` varchar(2) DEFAULT NULL,
  `base_bet` decimal(14,4) DEFAULT NULL,
  `bet` decimal(14,4) DEFAULT NULL,
  `bet_valid` decimal(14,4) DEFAULT NULL,
  `profit` decimal(14,4) DEFAULT NULL,
  `tax` decimal(14,4) DEFAULT NULL,
  `balance` decimal(14,4) DEFAULT NULL,
  `bonus` decimal(14,4) DEFAULT NULL,
  `result` text DEFAULT NULL,
  `round_id` varchar(20) DEFAULT NULL,
  `round_start_at` datetime DEFAULT NULL,
  `round_end_at` datetime DEFAULT NULL,
  `currency` varchar(5) DEFAULT NULL,
  `category` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`orderid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4