CREATE TABLE `betdata_tfgaming` (
  `orderid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `id_hash` int(10) unsigned NOT NULL COMMENT '投注单号hash',
  `id` varchar(64) DEFAULT NULL COMMENT '注单号',
  `bet_selection` varchar(64) DEFAULT NULL,
  `odds` decimal(20,10) DEFAULT NULL,
  `malay_odds` decimal(20,10) DEFAULT NULL,
  `euro_odds` decimal(20,10) DEFAULT NULL,
  `member_odds` decimal(20,10) DEFAULT NULL,
  `member_odds_style` varchar(10) DEFAULT NULL,
  `game_type_id` int(10) DEFAULT NULL,
  `game_type_name` varchar(32) DEFAULT NULL,
  `game_market_name` varchar(255) DEFAULT NULL,
  `market_option` varchar(10) DEFAULT NULL,
  `map_num` varchar(20) DEFAULT NULL,
  `bet_type_name` varchar(10) DEFAULT NULL,
  `competition_name` varchar(255) DEFAULT NULL,
  `event_id` int(10) DEFAULT NULL,
  `event_name` varchar(255) DEFAULT NULL,
  `event_datetime` datetime DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `settlement_datetime` datetime DEFAULT NULL,
  `modified_datetime` datetime DEFAULT NULL,
  `currency` varchar(4) DEFAULT NULL,
  `amount` decimal(20,10) DEFAULT NULL,
  `settlement_status` varchar(20) DEFAULT NULL,
  `is_unsettled` tinyint(1) DEFAULT NULL,
  `result_status` varchar(32) DEFAULT NULL,
  `result` varchar(255) DEFAULT NULL,
  `earnings` decimal(20,10) DEFAULT NULL,
  `handicap` decimal(20,10) DEFAULT NULL,
  `member_code` varchar(255) DEFAULT NULL,
  `request_source` varchar(20) DEFAULT NULL,
  `is_combo` tinyint(1) DEFAULT NULL,
  `ticket_type` varchar(10) DEFAULT NULL,
  `tickets` longtext DEFAULT NULL,
  `BetInfo` text DEFAULT NULL,
  PRIMARY KEY (`orderid`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=utf8mb4
