INSERT INTO Game_List SET GameVendor = 45, TheirGameId='ALL', GameEName='ALL', GameName='全部', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Soccer', GameEName='Soccer', GameName='足球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='BasketBall', GameEName='BasketBall', GameName='篮球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Football', GameEName='Football', GameName='美式足球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Ice Hockey', GameEName='Ice Hockey', GameName='冰棍球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Badminton', GameEName='Badminton', GameName='羽毛球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Pool/Snooker', GameEName='Pool/Snooker', GameName='撞球/斯诺克', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Motor Sport', GameEName='Motor Sport', GameName='赛车', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Tennis', GameEName='Tennis', GameName='网球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Baseball', GameEName='Baseball', GameName='棒球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Volleyball', GameEName='Volleyball', GameName='排球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Others', GameEName='Others', GameName='其它项目', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Golf', GameEName='Golf', GameName='高尔夫', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Boxing', GameEName='Boxing', GameName='拳击', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Cricket', GameEName='Cricket', GameName='板球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Table Tennis', GameEName='Table Tennis', GameName='乒乓', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Rugby', GameEName='Rugby', GameName='橄榄球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Handball', GameEName='Handball', GameName='手球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Cycling', GameEName='Cycling', GameName='自行车', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Athletics', GameEName='Athletics', GameName='竞技', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Beach Soccer', GameEName='Beach Soccer', GameName='沙滩足球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Futsal', GameEName='Futsal', GameName='室内足球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Entertainment', GameEName='Entertainment', GameName='独特', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Financial', GameEName='Financial', GameName='金融', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Darts', GameEName='Darts', GameName='飞镖', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Olympic', GameEName='Olympic', GameName='奥林匹克', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Lacrosse', GameEName='Lacrosse', GameName='袋棍球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Water Polo', GameEName='Water Polo', GameName='水球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Winter Sports', GameEName='Winter Sports', GameName='冬季运动', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Squash', GameEName='Squash', GameName='壁球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Field Hockey', GameEName='Field Hockey', GameName='草地曲棍球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Mixed Martial Arts', GameEName='Mixed Martial Arts', GameName='综合格斗', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='E Sports', GameEName='E Sports', GameName='电子竞技', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Gaelic Football', GameEName='Gaelic Football', GameName='盖尔式足球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Hurling', GameEName='Hurling', GameName='板棍球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Muay Thai', GameEName='Muay Thai', GameName='泰拳', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Aussie Rules Football', GameEName='Aussie Rules Football', GameName='澳洲足球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Bandy', GameEName='Bandy', GameName='班迪球', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
INSERT INTO Game_List SET GameVendor = 45, TheirGameId='Winter Olympics', GameEName='Winter Olympics', GameName='冬季奥林匹克运动会', IsOnline = 1, GameType = '1', FanShuiType = 'T', Note = N'';  
