USE platform_db_wrin ;

DROP TABLE  IF EXISTS betdata_evo ;

CREATE TABLE `betdata_evo` (
`RowId` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Id` VARCHAR(32) DEFAULT NULL,
  `startedAt` DATETIME NOT NULL,
  `settledAt` DATETIME NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `gameType` VARCHAR(32) NOT NULL,
  `playerId` VARCHAR(32) NOT NULL,
  `description` VARCHAR(32) NOT NULL DEFAULT '',
  `stake` DECIMAL(14,4) NOT NULL,
  `payout` DECIMAL(14,4) NOT NULL,
  `winlose` DECIMAL(14,4) NOT NULL,
  `betid` VARCHAR(64) NOT NULL DEFAULT '',
  `code` VARCHAR(32) NOT NULL DEFAULT '',
  `transactionId` BIGINT(20) UNSIGNED NOT NULL,
  `result` VARCHAR(1024) NOT NULL DEFAULT '',
  `betid_hash` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`RowId`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4
